### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by hudochenkov** [iamstarkov/iamstarkov.github.io#1]
https://iamstarkov.com/articles-dates/

![screen shot 2015-05-01 at 23 27 36](https://cloud.githubusercontent.com/assets/654597/7436851/2e7f08f0-f05a-11e4-9e8e-f9c28e7b783e.png)

**Comment by iamstarkov** [comment]
@hudochenkov have you been redirected automatically?

**Comment by iamstarkov** [comment]
landed in ce64d9d15f3d69b0c12652618efb702f2f6293d2. not published yet

**Comment by hudochenkov** [comment]
I've came from this tweet https://twitter.com/iamstarkov/status/593565168132579328 So it's autoredirect.

**Comment by iamstarkov** [comment]
great, then ssl is working

**Comment by iamstarkov** [comment]
just release fixes
