### ISSUE TITLE
Not so mobile friendly with images

### ISSUE THREAD

**Issue by hudochenkov** [iamstarkov/iamstarkov.github.io#2]
iPhone 5S, iOS 8
![file may 01 23 33 34](https://cloud.githubusercontent.com/assets/654597/7436892/9e260bd6-f05a-11e4-9d2c-f571a52bb900.png)

**Comment by iamstarkov** [comment]
thx, will fix it a bit later

**Comment by iamstarkov** [comment]
Should be fixed now
